<a href="https://colab.research.google.com/github/mukaseevru/ds-school/blob/main/lesson%207/HW_7_lesson.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Домашнее задание к 7 уроку.

**Дедлайн: 23.12.2020**

colab: https://colab.research.google.com/drive/1KLD5pDCa0ka_g1U4D2ExihaaEwXzfTPW?usp=sharing

**ФОРМАТ ОТЧЕТНОСТИ:** pdf-файл с решенными задачами (задачи 2-9), ноутбук с проверкой решения этих задач (при помощи numpy), и pdf файл с отчетом по 1-ой задаче (краткий пересказ статьи). Вы можете оформить решения с использованием Markdown (писать текст прямо в юпитер ноутбуке), Latex, Word или же решить в тетради и сформировать pdf из фото.

Итого: 2 pdf файла.

Все задания необходимо выполнять ВРУЧНУЮ. А также проверить корректность полученных результатов с использованием Numpy.

Туториал как писать "Latex-формулы" прямо в Юпитере:
https://www.youtube.com/watch?v=vSc25kdgecg

Ноутбук с примером формул: https://nbviewer.jupyter.org/github/postlogist/course_opt/blob/master/jupyter_tutorial/02_markdown.ipynb


## Пример


Найдем ранг матрицы 

$$\begin{pmatrix}
1 & 2 & 3 & 4 & 5\\ 
2 & 5 & 8 & 11 & 14\\ 
3 & 9 & 14 & 20 & 26\\ 
5 & 14 & 22 & 31 & 40
\end{pmatrix}.$$

Четвертая строка является суммой второй и третьей строк, а значит, ее можно отбросить:

$$\begin{pmatrix}
1 & 2 & 3 & 4 & 5\\ 
2 & 5 & 8 & 11 & 14\\ 
3 & 9 & 14 & 20 & 26
\end{pmatrix}.$$

Из второй и третьей строк вычтем первую, умноженную на $2$ и $3$ соответственно:

$$\begin{pmatrix}
1 & 2 & 3 & 4 & 5\\ 
0 & 1 & 2 & 3 & 4\\ 
0 & 2 & 5 & 8 & 11
\end{pmatrix}.$$

И вычтем из третьей строки вторую, умноженную на $2$:

$$\begin{pmatrix}
1 & 2 & 3 & 4 & 5\\ 
0 & 1 & 2 & 3 & 4\\ 
0 & 0 & 1 & 2 & 3
\end{pmatrix}.$$

Таким образом, ранг матрицы равен $3$.

In [1]:
# Проверка

import numpy as np
a = [1, 2, 3, 4, 5]
b = [2, 5, 8, 11, 14]
c = [3, 9, 14, 20, 26]
d = [5, 14, 22, 31, 40]

x = np.array([a, b, c, d])
r = np.linalg.matrix_rank(x)

print(f'Ранг матрицы: {r}')

Ранг матрицы: 3


# Задачи

**1.** Прочитать статью http://www.scielo.org.mx/pdf/cys/v18n3/v18n3a7.pdf и сделать следующее:

- Написать кратко (не более 300 слов (минимум 100), отчет в формате pdf) о различиях между cosine similarity и soft similarity. Привести примеры использования и написать собственный пример вычисления cosine similarity и soft similarity для произвольных векторов (не брать вектора из статьи! надо самим придумать координаты/размерность векторов)

__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$
    
__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

__5*.__ Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.


__6.__ Вычислить определитель (используйте любой удобный для вас способ вычисления определителя: через миноры, через перестановки или другой):

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

   б)
    
$$\begin{vmatrix}
8 & 4 & 6\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$
    
   в)

$$\begin{vmatrix}
2 & 3 & 4\\ 
5 & 6 & 7\\ 
8 & 9 & 10
\end{vmatrix}.$$


__7.__ Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2})$;
    
   б) $det(A^{T})$;
    
   в) $det(2A)$.
   
__8.__  Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

__9.__ Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

# Доп материалы
1. [Способы задать матрицу в NumPy](https://docs.scipy.org/doc/numpy-1.10.1/user/basics.creation.html).
2. [numpy.transpose](https://docs.scipy.org/doc/numpy-1.10.0/reference/generated/numpy.transpose.html).
3. [array.T](https://docs.scipy.org/doc/numpy-1.10.0/reference/generated/numpy.ndarray.T.html).
4. [Перемножение матриц в NumPy](https://docs.scipy.org/doc/numpy-1.10.0/reference/routines.linalg.html#matrix-and-vector-products).

5. [Определитель матрицы в NumPy](https://docs.scipy.org/doc/numpy-1.14.2/reference/generated/numpy.linalg.det.html)

6. [Ранг матрицы в NumPy](https://docs.scipy.org/doc/numpy-1.14.2/reference/generated/numpy.linalg.matrix_rank.html)

7. [Обращение матриц в NumPy](https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.inv.html)

Решение Домашнего задания

__1.__ Прочитать статью http://www.scielo.org.mx/pdf/cys/v18n3/v18n3a7.pdf и сделать следующее:

- Написать кратко (не более 300 слов (минимум 100), отчет в формате pdf) о различиях между cosine similarity и soft similarity. Привести примеры использования и написать собственный пример вычисления cosine similarity и soft similarity для произвольных векторов (не брать вектора из статьи! надо самим придумать координаты/размерность векторов)

<a href='https://github.com/mukaseevru/ds-school/blob/main/lesson%207/HW_7_lesson_(1).pdf'>Ссылка на PDF</a>

In [2]:
import gensim.downloader as api
from gensim import corpora
from gensim.matutils import softcossim
fasttext_model300 = api.load('fasttext-wiki-news-subwords-300')

In [3]:
# Определим две фразы
sent_1 = 'Саша очень любит играть в футбол'.split()
sent_2 = 'Оля каждый день играет в футбол на позиции вратаря'.split()

# Подготовим словарь слов
documents = [sent_1, sent_2]
dictionary = corpora.Dictionary(documents)

# Подготовим матрицу подобия
similarity_matrix = fasttext_model300.similarity_matrix(dictionary)

# Конвертируем предложения в векторы
sent_1 = dictionary.doc2bow(sent_1)
sent_2 = dictionary.doc2bow(sent_2)

# Посчитаем мягкое косинусное сходство
print(softcossim(sent_1, sent_2, similarity_matrix))

0.8017683002913699


__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

In [4]:
import numpy as np
A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1], [0, 5]])
print(f'Матрица A\n{A}\n')
print(f'Матрица B\n{B}\n')
print(f'Сумма\n{A + B}')
print(f'Произведение\n{np.dot(A, B)}')

Матрица A
[[ 1 -2]
 [ 3  0]]

Матрица B
[[ 4 -1]
 [ 0  5]]

Сумма
[[ 5 -3]
 [ 3  5]]
Произведение
[[  4 -11]
 [ 12  -3]]


__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

In [5]:
A = np.array([[1, 7], [3, -6]])
B = np.array([[0, 5], [2, -1]])
C = np.array([[2, -4], [1, 1]])
print(f'Матрица A\n{A}\n')
print(f'Матрица B\n{B}\n')
print(f'Матрица C\n{C}\n')
print(f'Линейная комбинация 3A-2B+4C\n{3*A - 2*B + 4*C}')

Матрица A
[[ 1  7]
 [ 3 -6]]

Матрица B
[[ 0  5]
 [ 2 -1]]

Матрица C
[[ 2 -4]
 [ 1  1]]

Линейная комбинация 3A-2B+4C
[[ 11  -5]
 [  9 -12]]


__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

In [6]:
A = np.array([[4, 1], [5, -2], [2, 3]])
print(f'Матрица:\n{A}')
print(f'Транспонированная матрица:\n{A.T}')

Матрица:
[[ 4  1]
 [ 5 -2]
 [ 2  3]]
Транспонированная матрица:
[[ 4  5  2]
 [ 1 -2  3]]


$AA^{T}$:

In [7]:
print(f'{np.dot(A, A.T)}\n')

[[17 18 11]
 [18 29  4]
 [11  4 13]]



$A^{T}A$

In [8]:
print(f'{np.dot(A.T, A)}\n')

[[45  0]
 [ 0 14]]



__5*.__ Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [9]:
# array_1 - первая матрица размерностью m строк на n столбцов
# array_2 - вторая матрица размерностью n строк на k столбцов
def multy_matrix(array_1, array_2):
  array_1_m = array_1.shape[0]
  array_1_n = array_1.shape[1]
  array_2_n = array_2.shape[0]
  array_2_k = array_2.shape[1]
  if array_1_n == array_2_n:
    result = [[0 for x in range(array_2_k)] for y in range(array_2_k)]
    for k in range(array_2_k):
      for m in range(array_2_k):
        temp = 0
        for n in range(array_1_n):
            temp += array_1[m][n] * array_2[n][k]
        result[m][k] = temp
    return result
  else:
    print('Ошибка в размерности матриц')
    return False
multy_matrix(A, A.T)

[[17, 18, 11], [18, 29, 4], [11, 4, 13]]

__6.__ Вычислить определитель (используйте любой удобный для вас способ вычисления определителя: через миноры, через перестановки или другой):

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

In [10]:
x = np.pi
A = np.array([[np.sin(x), -np.cos(x)], [np.cos(x), np.sin(x)]])
print(f'Матрица:\n{A}')
print(f'Определитель:\n{np.linalg.det(A):.0f}')

Матрица:
[[ 1.2246468e-16  1.0000000e+00]
 [-1.0000000e+00  1.2246468e-16]]
Определитель:
1


   б)
    
$$\begin{vmatrix}
8 & 4 & 6\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$

In [11]:
A = np.array([[8, 4, 6], [0, 5, 1], [0, 0, 9]])
print(f'Матрица:\n{A}')
print(f'Определитель:\n{np.linalg.det(A):.0f}')

Матрица:
[[8 4 6]
 [0 5 1]
 [0 0 9]]
Определитель:
360


   в)

$$\begin{vmatrix}
2 & 3 & 4\\ 
5 & 6 & 7\\ 
8 & 9 & 10
\end{vmatrix}.$$

In [12]:
A = np.array([[2, 3, 4], [5, 6, 7], [8, 9, 10]])
print(f'Матрица:\n{A}')
print(f'Определитель:\n{np.linalg.det(A):.0f}')

Матрица:
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
Определитель:
0


__7.__ Определитель матрицы $A$ равен $4$. Найти:

In [13]:
# Возьмем матрицу для примера
A = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 4]])
print(f'Матрица:\n{A}')
print(f'Определитель:\n{np.linalg.det(A):.0f}')

Матрица:
[[1 0 0]
 [0 1 0]
 [0 0 4]]
Определитель:
4


а) $det(A^{2})$;

In [14]:
print(f'Определитель:\n{np.linalg.det(np.dot(A,A)):.0f}')

Определитель:
16


б) $det(A^{T})$;

In [15]:
print(f'Определитель:\n{np.linalg.det(A.T):.0f}')

Определитель:
4


в) $det(2A)$.

In [16]:
# Зависит от рамерности матрицы
print(f'Определитель:\n{np.linalg.det(2*A):.0f}')

Определитель:
32


__8.__  Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

In [17]:
# Матрица вырожденная, если определитель равен 0
A = np.array([[-2, 7, -3], [4, -14, 6], [-3, 7, 13]])
print(f'Матрица:\n{A}')
print(f'Определитель:\n{np.linalg.det(A):.0f}')

Матрица:
[[ -2   7  -3]
 [  4 -14   6]
 [ -3   7  13]]
Определитель:
0


__9.__ Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

In [18]:
A = np.array([[1, 2, 3], [1, 1, 1], [2, 3, 4]])
r = np.linalg.matrix_rank(A)

print(f'Ранг матрицы: {r}')

Ранг матрицы: 2


   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

In [19]:
A = np.array([[0, 0, 2, 1], [0, 0, 2, 2], [0, 0, 4, 3], [2, 3, 5, 6]])
r = np.linalg.matrix_rank(A)

print(f'Ранг матрицы: {r}')

Ранг матрицы: 3


<a href='https://github.com/mukaseevru/ds-school/blob/main/lesson%207/HW_7_lesson_(2-9).pdf'>Ссылка на PDF</a>